#!/bin/sh
# Remove trailers automáticos de ferramentas da mensagem de commit.
# Instalar: cp scripts/git-hooks/prepare-commit-msg .git/hooks/prepare-commit-msg && chmod +x .git/hooks/prepare-commit-msg
FILE="$1"
[ -f "$FILE" ] || exit 0
sed -i '/^[[:space:]]*[Mm]ade-with[[:space:]]*:/d' "$FILE"
exit 0
