name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # Nx Cloud task distribution
      - run: pnpm nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      - run: pnpm exec playwright install --only-shell

      - run: pnpm nx record -- echo Hello World
      - run: pnpm nx run-many -t lint test build typecheck e2e

      - run: pnpm nx fix-ci
        if: always()
